package hu.oe.nik.szfmv.automatedcar.bus;

public enum SignalEnum {
    GASPEDAL, BREAKPEDAL, STEERINGWHEEL, AUTOTRANSMISSION, REVOLUTION, SPEED, POSX, POSY, INDEX, TESTSIGNAL, LASTROADSIGN,
    AEB_OFF, AEB_WARN, AEB_INTERVENE
}
