package hu.oe.nik.szfmv.environment.util;

public enum SensorType {
    CAMERA, RADAR, ULTRASONIC_FR, ULTRASONIC_FL, ULTRASONIC_RL, ULTRASONIC_RR,
    ULTRASONIC_LSF, ULTRASONIC_LSB, ULTRASONIC_RSF, ULTRASONIC_RSB
}
